server:
  port: 8080

spring:
  application:
    name: gatewayModule
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods: "*"
            allow-credentials: true
      routes:
        - id: spring-boot
          #uri: lb://spring-boot
          uri: http://localhost:8084/
          #uri: http://172.20.0.3:8080
          predicates:
            - Path=/index/**
        - id: spring-authentication
          uri: http://localhost:8081/
          predicates:
            - Path=/api/**
          filters:
            name: JwtAuthenticationFilter